version: "3"
services:
  postgres:
    image: postgres:15.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: application
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./volumes/postgres