### Permissions

###
GET {{host}}/permissions?page=0&size=10&sort=id&direction=DESC
Authorization: Bearer {{oauthToken}}

###
POST {{host}}/permissions
Content-Type: application/json
Authorization: Bearer {{oauthToken}}

{"name": "test-{{$random.integer(0, 1000)}}", "description": "test description coroutine"}

> {%
client.global.set("permissionId", response.body.id)
 %}

###
GET {{host}}/permissions/{{permissionId}}
Authorization: Bearer {{oauthToken}}

###
PUT {{host}}/permissions/{{permissionId}}
Content-Type: application/json
Authorization: Bearer {{oauthToken}}

{"name": "test-coroutine-changed", "description": "test description coroutine changed!", "version": 0}

###
PUT {{host}}/permissions/{{permissionId}}/jpql
Content-Type: application/json
Authorization: Bearer {{oauthToken}}

{"name": "test-coroutine-changed", "description": "test description coroutine changed via jpql!", "version": 0}

###
DELETE {{host}}/permissions/{{permissionId}}
Authorization: Bearer {{oauthToken}}

> {%
client.global.set("permissionId", null)
 %}

### todo: move

###
GET {{host}}/external/{{$random.integer(0, 1000)}}
Authorization: Bearer {{oauthToken}}

###
GET {{host}}/error?message=foo
Authorization: Bearer {{oauthToken}}
