### Permissions

###
GET {{host}}/permissions?page=0&size=10&sort=id&direction=DESC
Authorization: Bearer {{oauthToken}}

###
GET {{host}}/permissions/count?search=test&createdFrom=1772265820594&createdBy=05dbf0b6-057b-44b4-aeaa-d83d662c5833
Authorization: Bearer {{oauthToken}}

###
POST {{host}}/permissions
Content-Type: application/json
Authorization: Bearer {{oauthToken}}

{"name": "test-{{$random.integer(0, 1000)}}", "description": "test description coroutine"}

> {%
client.global.set("permissionId", response.body.id)
 %}

###
GET {{host}}/permissions/{{permissionId}}
Authorization: Bearer {{oauthToken}}

###
PUT {{host}}/permissions/{{permissionId}}
Content-Type: application/json
Authorization: Bearer {{oauthToken}}

{"name": "test-coroutine-changed", "description": "test description coroutine changed!", "version": 1}

###
DELETE {{host}}/permissions/{{permissionId}}
Authorization: Bearer {{oauthToken}}

> {%
client.global.set("permissionId", null)
 %}

### external

### HTTP
GET {{host}}/external/{{$random.integer(0, 1000)}}
Authorization: Bearer {{oauthToken}}

### HTTP -> GRPC
GET {{host}}/external/grpc/{{$random.integer(0, 1000)}}
Authorization: Bearer {{oauthToken}}

### GRPC Unary call
GRPC localhost:9082/com.softeno.template.grpc.SampleGrpcService/Echo

{
  "data": "123"
}

### GRPC Server streaming
GRPC localhost:9082/com.softeno.template.grpc.SampleGrpcService/EchoServerStream

{
  "data": "hello"
}

### GRPC Client streaming & Bidirectional streaming - not supported in IDEA

### sample-secured

###
GET {{host}}/sample-secured/{{$random.integer(0, 1000)}}
Authorization: Bearer {{oauthToken}}

###
POST {{host}}/sample-secured
Content-Type: application/json
Authorization: Bearer {{oauthToken}}

{"data": "sample data: {{$uuid}}"}

###
PUT {{host}}/sample-secured/{{$random.integer(0, 1000)}}
Content-Type: application/json
Authorization: Bearer {{oauthToken}}

{"data": "sample data: {{$uuid}} change"}

###
DELETE {{host}}/sample-secured/{{$random.integer(0, 1000)}}
Authorization: Bearer {{oauthToken}}

